version: "3.9"
services:
  web:
    build: .
    ports:
      - "6000:6000"
    command: python manage.py runserver 0.0.0.0:6000
    volumes:
      - .:/code  

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: