# Generated by Django 2.2.24 on 2022-01-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
